---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alexizys/projects/flies.alexsol.is
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp style.css.js $DEPLOYPATH
    - /bin/cp -R fly $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH