---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alexizys/flies.alexsol.is
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R fly $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH